version: '3'
services:
 web:
   build:
    context: 'config-docker-php'
    dockerfile: Dockerfile    
   ports:
      - "8083:80"
   volumes:
      - ./:/var/www/html/personas/
 dbmysql:
    image: mysql:5.7.33
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: guilleDB
    volumes:
     - ./mysql-data:/var/lib/mysql
 phpmyadmin:
    image: phpmyadmin
    depends_on:
      - dbmysql
    environment:
          - PMA_ARBITRARY=1
    ports:
        - "8084:80"
